/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.elmar_baumann.nb.slclock.alarmclock;

/**
 * @author Elmar Baumann
 */
public class AlarmEventsPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    public AlarmEventsPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        buttonAddAlarmEvent = new javax.swing.JButton();
        buttonRemoveSelAlarmEvents = new javax.swing.JButton();
        scrollPaneAlarmEvents = new javax.swing.JScrollPane();
        panelAlarmEvents = new javax.swing.JPanel();

        buttonAddAlarmEvent.setText("+"); // NOI18N
        buttonAddAlarmEvent.setToolTipText(org.openide.util.NbBundle.getMessage(AlarmEventsPanel.class, "AlarmEventsPanel.buttonAddAlarmEvent.toolTipText")); // NOI18N
        buttonAddAlarmEvent.setMargin(new java.awt.Insets(2, 2, 2, 2));

        buttonRemoveSelAlarmEvents.setText("-"); // NOI18N
        buttonRemoveSelAlarmEvents.setToolTipText(org.openide.util.NbBundle.getMessage(AlarmEventsPanel.class, "AlarmEventsPanel.buttonRemoveSelAlarmEvents.toolTipText")); // NOI18N
        buttonRemoveSelAlarmEvents.setMargin(new java.awt.Insets(2, 2, 2, 2));

        javax.swing.GroupLayout panelAlarmEventsLayout = new javax.swing.GroupLayout(panelAlarmEvents);
        panelAlarmEvents.setLayout(panelAlarmEventsLayout);
        panelAlarmEventsLayout.setHorizontalGroup(
            panelAlarmEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );
        panelAlarmEventsLayout.setVerticalGroup(
            panelAlarmEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );

        scrollPaneAlarmEvents.setViewportView(panelAlarmEvents);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPaneAlarmEvents, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAddAlarmEvent, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonRemoveSelAlarmEvents, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonAddAlarmEvent, buttonRemoveSelAlarmEvents});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonAddAlarmEvent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRemoveSelAlarmEvents)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(scrollPaneAlarmEvents, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonAddAlarmEvent, buttonRemoveSelAlarmEvents});

    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddAlarmEvent;
    private javax.swing.JButton buttonRemoveSelAlarmEvents;
    private javax.swing.JPanel panelAlarmEvents;
    private javax.swing.JScrollPane scrollPaneAlarmEvents;
    // End of variables declaration//GEN-END:variables

}
