package de.elmar_baumann.nb.slclock.alarmclock;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.Icon;
import javax.swing.SwingUtilities;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.util.ImageUtilities;
import org.openide.util.NbBundle;

/**
 * @author Elmar Baumann
 */
public class AlarmClockPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    private static final Icon ICON_RUNS = ImageUtilities.loadImageIcon("/de/elmar_baumann/nb/slclock/icons/alarm-runs.png", false);
    private static final Icon ICON_PAUSES = ImageUtilities.loadImageIcon("/de/elmar_baumann/nb/slclock/icons/alarm-pauses.png", false);
    private final AlarmEventsModel model = new AlarmEventsModel();

    public AlarmClockPanel() {
        initComponents();
        model.init();
        setIcon();
        model.addPropertyChangeListener(iconListener);
        addMouseListener(preferencesDialogDisplayer);
        labelAlarmClock.addMouseListener(preferencesDialogDisplayer);
        setToolTipText(labelAlarmClock.getToolTipText());
    }

    private void setIcon() {
        labelAlarmClock.setIcon(model.getEventCount() > 0
                ? ICON_RUNS
                : ICON_PAUSES);
    }

    private final PropertyChangeListener iconListener = new PropertyChangeListener() {

        @Override
        public void propertyChange(PropertyChangeEvent evt) {
            if (AlarmEventsModel.PROPERTY_EVENTS.equals(evt.getPropertyName())) {
                setIcon();
            }
        }
    };

    private final MouseListener preferencesDialogDisplayer = new MouseAdapter() {

        @Override
        public void mouseClicked(MouseEvent e) {
            if (SwingUtilities.isLeftMouseButton(e)) {
                DialogDescriptor dd = new DialogDescriptor(
                       new AlarmEventsPanel(model), // innerPane
                        NbBundle.getMessage(AlarmClockPanel.class, "AlarmClockPanel.PreferencesDialog.Title"), // title
                        true, // modal
                        new Object[] {DialogDescriptor.OK_OPTION}, //options
                        DialogDescriptor.OK_OPTION, // initialValue
                        DialogDescriptor.DEFAULT_ALIGN, // optionsAlign
                        null, // helpCtx
                        null //bl
                );
                DialogDisplayer.getDefault().notify(dd);
            }
        }
    };

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAlarmClock = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        labelAlarmClock.setIcon(ICON_PAUSES);
        labelAlarmClock.setToolTipText(org.openide.util.NbBundle.getMessage(AlarmClockPanel.class, "AlarmClockPanel.labelAlarmClock.toolTipText")); // NOI18N
        add(labelAlarmClock, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAlarmClock;
    // End of variables declaration//GEN-END:variables

}
