package de.elmar_baumann.nb.slclock.alarmclock;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.SwingUtilities;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.util.NbBundle;

/**
 * @author Elmar Baumann
 */
public class AlarmClockPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    public AlarmClockPanel() {
        initComponents();
        addMouseListener(preferencesDialogDisplayer);
        labelAlarmClock.addMouseListener(preferencesDialogDisplayer);
        setToolTipText(labelAlarmClock.getToolTipText());
    }

    private final MouseListener preferencesDialogDisplayer = new MouseAdapter() {

        @Override
        public void mouseClicked(MouseEvent e) {
            if (SwingUtilities.isLeftMouseButton(e)) {
                DialogDescriptor dd = new DialogDescriptor(
                       new AlarmEventsPanel(), // innerPane
                        NbBundle.getMessage(AlarmClockPanel.class, "AlarmClockPanel.PreferencesDialog.Title"), // title
                        true, // modal
                        new Object[] {DialogDescriptor.OK_OPTION}, //options
                        DialogDescriptor.OK_OPTION, // initialValue
                        DialogDescriptor.DEFAULT_ALIGN, // optionsAlign
                        null, // helpCtx
                        null //bl
                );
                DialogDisplayer.getDefault().notify(dd);
            }
        }
    };

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        labelAlarmClock = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        labelAlarmClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/elmar_baumann/nb/slclock/icons/alarm-pauses.png"))); // NOI18N
        labelAlarmClock.setToolTipText(org.openide.util.NbBundle.getMessage(AlarmClockPanel.class, "AlarmClockPanel.labelAlarmClock.toolTipText")); // NOI18N
        add(labelAlarmClock, new java.awt.GridBagConstraints());
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAlarmClock;
    // End of variables declaration//GEN-END:variables

}
