package de.elmar_baumann.nb.slclock.alarmclock;

import java.awt.EventQueue;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.Icon;
import javax.swing.SwingUtilities;
import org.netbeans.api.annotations.common.StaticResource;
import org.openide.util.ImageUtilities;

/**
 * @author Elmar Baumann
 */
public class AlarmClockDisplayPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    @StaticResource private static final String ICON_PATH_ALARM_RUNS = "de/elmar_baumann/nb/slclock/icons/alarm-runs.png";
    @StaticResource private static final String ICON_PATH_ALARM_PAUSES = "de/elmar_baumann/nb/slclock/icons/alarm-pauses.png";
    private static final Icon ICON_ALARM_RUNS = ImageUtilities.loadImageIcon(ICON_PATH_ALARM_RUNS, false);
    private static final Icon ICON_ALARM_PAUSES = ImageUtilities.loadImageIcon(ICON_PATH_ALARM_PAUSES, false);

    public AlarmClockDisplayPanel() {
        initComponents();
        setIcon();
        addMouseListener(preferencesDialogDisplayer);
        AlarmEventsModel.getInstance().addPropertyChangeListener(iconUpdater);
        labelAlarmClock.addMouseListener(preferencesDialogDisplayer);
        setVisible(AlarmEventsModel.getInstance().isShowIcon());
    }

    private void setIcon() {
        labelAlarmClock.setIcon(AlarmEventsModel.getInstance().getRunningEventsCount() > 0
                ? ICON_ALARM_RUNS
                : ICON_ALARM_PAUSES);
    }

    private final PropertyChangeListener iconUpdater = new PropertyChangeListener() {
        @Override
        public void propertyChange(final PropertyChangeEvent evt) {
            EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    String propertyName = evt.getPropertyName();
                    if (AlarmEventsModel.PROPERTY_EVENTS.equals(propertyName)) {
                        setIcon();
                    } else if (AlarmEventsModel.PROPERTY_SHOW_ICON.equals(propertyName)) {
                        setVisible((boolean) evt.getNewValue());
                    }
                }
            });
        }
    };

    private final MouseListener preferencesDialogDisplayer = new MouseAdapter() {

        @Override
        public void mouseClicked(MouseEvent e) {
            if (SwingUtilities.isLeftMouseButton(e)) {
                AlarmEventsModel.getInstance().showSettingsGui();
            }
        }
    };

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAlarmClock = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        labelAlarmClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/elmar_baumann/nb/slclock/icons/alarm-pauses.png"))); // NOI18N
        add(labelAlarmClock, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAlarmClock;
    // End of variables declaration//GEN-END:variables

}
