package de.elmar_baumann.nb.slclock.alarmclock;

/**
 * @author Elmar Baumann
 */
public class AlarmEventsPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    public AlarmEventsPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        scrollPaneAlarmEvents = new javax.swing.JScrollPane();
        panelAlarmEvents = new javax.swing.JPanel();
        panelButtons = new javax.swing.JPanel();
        buttonAddAlarmEvent = new javax.swing.JButton();
        buttonRemoveSelAlarmEvents = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        scrollPaneAlarmEvents.setPreferredSize(new java.awt.Dimension(250, 150));

        panelAlarmEvents.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panelAlarmEventsLayout = new javax.swing.GroupLayout(panelAlarmEvents);
        panelAlarmEvents.setLayout(panelAlarmEventsLayout);
        panelAlarmEventsLayout.setHorizontalGroup(
            panelAlarmEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        panelAlarmEventsLayout.setVerticalGroup(
            panelAlarmEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );

        scrollPaneAlarmEvents.setViewportView(panelAlarmEvents);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        add(scrollPaneAlarmEvents, gridBagConstraints);

        panelButtons.setLayout(new java.awt.GridBagLayout());

        buttonAddAlarmEvent.setText("+"); // NOI18N
        buttonAddAlarmEvent.setToolTipText(org.openide.util.NbBundle.getMessage(AlarmEventsPanel.class, "AlarmEventsPanel.buttonAddAlarmEvent.toolTipText")); // NOI18N
        buttonAddAlarmEvent.setMargin(new java.awt.Insets(2, 2, 2, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelButtons.add(buttonAddAlarmEvent, gridBagConstraints);

        buttonRemoveSelAlarmEvents.setText("-"); // NOI18N
        buttonRemoveSelAlarmEvents.setToolTipText(org.openide.util.NbBundle.getMessage(AlarmEventsPanel.class, "AlarmEventsPanel.buttonRemoveSelAlarmEvents.toolTipText")); // NOI18N
        buttonRemoveSelAlarmEvents.setMargin(new java.awt.Insets(2, 2, 2, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        panelButtons.add(buttonRemoveSelAlarmEvents, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 10);
        add(panelButtons, gridBagConstraints);
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddAlarmEvent;
    private javax.swing.JButton buttonRemoveSelAlarmEvents;
    private javax.swing.JPanel panelAlarmEvents;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JScrollPane scrollPaneAlarmEvents;
    // End of variables declaration//GEN-END:variables

}
