package de.elmar_baumann.nb.slclock.alarmclock;

import javax.swing.Icon;
import org.openide.util.ImageUtilities;

/**
 * @author Elmar Baumann
 */
public class AlarmEventPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    private static final Icon iconStart = ImageUtilities.loadImageIcon("de/elmar_baumann/nb/slclock/icons/start.png", false);
    private static final Icon iconPause = ImageUtilities.loadImageIcon("de/elmar_baumann/nb/slclock/icons/pause.png", false);

    public AlarmEventPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        buttonStartPause = new javax.swing.JButton();
        labelDisplayName = new javax.swing.JLabel();

        buttonStartPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/elmar_baumann/nb/slclock/icons/start.png"))); // NOI18N
        buttonStartPause.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonStartPause)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDisplayName))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(labelDisplayName)
                .addComponent(buttonStartPause))
        );
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonStartPause;
    private javax.swing.JLabel labelDisplayName;
    // End of variables declaration//GEN-END:variables

}
