package de.elmar_baumann.nb.slclock;

/**
 * @author Elmar Baumann
 */
public class StatusLineClockPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    public StatusLineClockPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        separator = new javax.swing.JSeparator();
        panelClock = new de.elmar_baumann.nb.slclock.clock.ClockPanel();
        panelAlarmClock = new de.elmar_baumann.nb.slclock.alarmclock.AlarmClockPanel();
        panelTimer = new de.elmar_baumann.nb.slclock.timer.TimerPanel();

        setLayout(new java.awt.GridBagLayout());

        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        separator.setPreferredSize(new java.awt.Dimension(2, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        add(separator, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(panelClock, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        add(panelAlarmClock, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        add(panelTimer, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.elmar_baumann.nb.slclock.alarmclock.AlarmClockPanel panelAlarmClock;
    private de.elmar_baumann.nb.slclock.clock.ClockPanel panelClock;
    private de.elmar_baumann.nb.slclock.timer.TimerPanel panelTimer;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables

}
